engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
  fixme:
    enabled: true
ratings:
  paths:
    - "**.php"
exclude_paths:
  - "package-lock.json"
  - "alias"
  - "after.sh"
  - "bootstrap/*"
  - "database/*"
  - "resources/lang/*"
  - "resources/views/*"
  - "storage/*"
  - "tests/*"
  - "vendor/**/*"
